language: cpp
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install libspdlog-dev -y
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- sudo dpkg -i ip_filter-*.deb && ip_filter
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u libhet:$BINTRAY_API_KEY "https://api.bintray.com/content/libhet/OTUS_CPP/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
